Itchy Pebble Piranha

Medium

# Users are sometimes blocked from withdrawing their FIXED ETH when the vault is ongoing, because of an invalid request IDs check

### Summary

When FIXED users withdraw their deposits, a request is sent to Lido and gets fulfilled later. Lido returns the request IDs for the withdrawals, these IDs are saved in mappings according to the time they're being requested, before the vault starts, before the vault ends, ...

When withdrawing before the vault starts, the protocol checks if there are previous "before start" pending withdrawal, and if so, it reverts, which makes sense, as it is saved per address:
```solidity
require(fixedToVaultNotStartedWithdrawalRequestIds[msg.sender].length == 0, "WAR");
```
However, when withdrawing after the vault starts and before it ends, the protocol also checks if there are "before start" pending withdrawals, which doesn't make sense, as it blocks users from requesting ongoing withdrawals whenever they want, they'll have to wait until the "before start" request is fulfilled on Lido. 
```solidity
require(
  fixedToVaultOngoingWithdrawalRequestIds[msg.sender].requestIds.length == 0 &&
    fixedToVaultNotStartedWithdrawalRequestIds[msg.sender].length == 0,
  "WAR"
);
```

### Root Cause

`LidoVault::withdraw` checks if the user has a "before vault start" pending withdrawal before allowing him to withdraw his ongoing balance, [here](https://github.com/sherlock-audit/2024-08-saffron-finance/blob/main/lido-fiv/contracts/LidoVault.sol#L476).

### Impact

Users are temporarily blocked from withdrawing their deposited amount while having a pending "before vault start" withdrawal.

### PoC

Add the following test in `lido-fiv/test/1.LidoVault.test.ts`:

```typescript
it("BUG - Can't withdraw ongoing fixed withdrawals", async () => {
  const { lidoVault, addr1, addr2, addr3 } = await loadFixture(deployLidoVaultFixture)

  // User 1 deposits 100 FIXED
  await lidoVault.connect(addr1).deposit(SIDE.FIXED, { value: parseEther('100') })

  // User 1 withdraws 100 FIXED
  await lidoVault.connect(addr1).withdraw(SIDE.FIXED)

  // Withdrawal is sent to Lido
  expect(
    (await lidoVault.getFixedToVaultNotStartedWithdrawalRequestIds(addr1.address)).length
  ).to.equal(1)

  // User 1 deposits 100 FIXED
  await lidoVault.connect(addr1).deposit(SIDE.FIXED, { value: parseEther('700') })
  // User 3 deposits 200 FIXED
  await lidoVault.connect(addr3).deposit(SIDE.FIXED, { value: parseEther('300') })
  // user 2 deposits 30 VARIABLE
  await lidoVault.connect(addr2).deposit(SIDE.VARIABLE, { value: parseEther('30') })

  // Vault has started
  expect(await lidoVault.isStarted()).to.equal(true)

  // User 1 claims FIXED premium
  await lidoVault.connect(addr1).claimFixedPremium()

  // User 1 can't withdraw his ongoing FIXED
  await expect(lidoVault.connect(addr1).withdraw(SIDE.FIXED)).to.be.revertedWith('WAR')
})
```

### Mitigation

Remove `fixedToVaultNotStartedWithdrawalRequestIds[msg.sender].length == 0` from the ongoing FIXED withdrawal check, https://github.com/sherlock-audit/2024-08-saffron-finance/blob/main/lido-fiv/contracts/LidoVault.sol#L474-L478.